"""Prompts module."""

from .diagnosis_prompts import (
    CARDIOVASCULAR_PROMPT,
    NEUROLOGICAL_FINAL_PROMPT,
)

from .synthesis_prompts import (
    SYNTHESIS_PROMPT)

from .patient_prompts import (
    PATIENT_DATA_THINK_PROMPT,
    PATIENT_DATA_EXTRACT_PROMPT,
)

from .planner_prompts import (
    PLANNER_SYSTEM_PROMPT,
    PLANNER_USER_PROMPT,
)

from .supervisor_prompts import (
    SUPERVISOR_LLM_PROMPT,
    SUPERVISOR_SYNTHESIS_PROMPT,
    SUPERVISOR_VALIDATION_PROMPT,
)

__all__ = ["SYNTHESIS_PROMPT",
    "CARDIOVASCULAR_PROMPT",
    "NEUROLOGICAL_PROMPT",
    "NEUROLOGICAL_FINAL_PROMPT",
    "PATIENT_DATA_EXTRACT_PROMPT",
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_USER_PROMPT",
    "SUPERVISOR_LLM_PROMPT",
    "SUPERVISOR_SYNTHESIS_PROMPT",
    "SUPERVISOR_VALIDATION_PROMPT",
]